image: 192.168.0.11:5000/docker:v1

services:
  - 192.168.0.11:5000/docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: dev

stages:
  - build
  - package
  - deploy

maven-build:
  image: 192.168.0.11:5000/gitlabci:v1
  stage: build
  #script: "mvn package -B"
  script: "mvn package -B -Dmaven.test.skip=true"
  
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
    - docker build --build-arg SPRING_PROFILES_ACTIVE=dev  -t 192.168.0.11:5000/customs-dev:v1 .
    - docker push  192.168.0.11:5000/customs-dev:v1
    - docker build --build-arg SPRING_PROFILES_ACTIVE=test -t 182.252.135.90:5000/customs-test:v1 .

k8s-deploy:
  image: 192.168.0.11:5000/gitlabci:v1
  stage: deploy
  script:
    - echo "deploy start"
    - curl http://192.168.0.11:9999/deployhelper/deploy/customs
    - echo "deploy ok"



#k8s-deploy:
#  image: google/cloud-sdk
#  stage: deploy
#  script:
#  - echo "$GOOGLE_KEY" > key.json
#  - gcloud auth activate-service-account --key-file key.json
#  - gcloud config set compute/zone europe-west1-c
#  - gcloud config set project actuator-sample
#  - gcloud config set container/use_client_certificate True
#  - gcloud container clusters get-credentials actuator-sample
#  - kubectl delete secret registry.gitlab.com
#  - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=marcolenzo --docker-password=$REGISTRY_PASSWD --docker-email=lenzo.marco@gmail.com
#  - kubectl apply -f deployment.yml
